name: saltproc-env-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - openmc
  - numpy
  - pytables
  - networkx
  - pydot
  - pytest
  - jsonschema
  - pip:
    - git+https://github.com/CORE-GATECH-GROUP/serpent-tools.git
    - argparse
